#1440×642
title = "En Tinta Verde"
baseURL = "https://entintaverde.org"
languageCode = "es-mx"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "es"
contentDir = "content/es"
SectionPagesMenu = "main"
#Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[pagination]
  pagerSize = 2
  #path = 'page'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Frida Martinez | Damian Flores"
  favicon = "/img/favicon.ico"
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  recent_posts_number = 3
